[workspace]
members = [
    "counter_game",
    "maximizing_xor",
    "lonely_integer",
    "abbreviation",
    "sherlock_and_cost",
    "the_coin_change_problem",
    "heap_test",
    "synchronous_shopping",
    "journey_to_the_moon",
    "generate_parentheses",
    "main",
    "algo_lib",
]
