[workspace]
members = [
    "d_many_perfect_squares",
    "c_equal_frequencies",
    "b_going_to_the_cinema",
    "a_parallel_projection",
    "b_quick_sort",
    "a_greatest_convex",
    "a_make_it_beautiful",
    "main",
    "algo_lib",
]
