[package]
name = "c_equal_frequencies"
version = "0.1.0"
edition = "2021"

[dependencies]
algo_lib = {path = "../algo_lib"}
rand = "0.8.5"

[build-dependencies]
rust_competitive_helper_util = {git = "https://github.com/rust-competitive-helper/rust-competitive-helper"}
